set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# automatically reorder windows
set -g renumber-windows on

# use current directory as path for new windows and panes
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Enable mouse mode
set -g mouse on

run '~/.tmux/plugins/tpm/tpm'

